TREAT: "treatment.tsv"
CONTROL: "control.tsv"
TREAT_NAME : "stress" 
CONTROL_NAME : "wildtype"
WORKDIR: '/rds/project/yhbl2/rds-yhbl2-genehunter/SM/RNASeq'
STRAND: 2
GENOME: "/rds/project/rds-O11U8YqSuCk/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/WholeGenomeFasta/genome.fa"
GTF: "/rds/project/rds-O11U8YqSuCk/SM/annotations/Mus_musculus/Ensembl/GRCm38/Annotation/Genes/genes.gtf" 
INDEX: "/rds/project/rds-O11U8YqSuCk/SM/annotations/Mus_musculus/Ensembl/GRCm38/Sequence/Bowtie2Index/genome"
N : 2 #Number of replicates 
PAIRED: TRUE  #PAIRED is either TRUE or FALSE  
MEMORY: "-Xmx40g" #for 40giga, change as much giga as you have 
